CREATE TABLE IF NOT EXISTS `documentation` (
  `id` INT(11) UNSIGNED PRIMARY KEY AUTO_INCREMENT,
  `wiki` VARCHAR(255) NOT NULL DEFAULT '',
  `confluence` VARCHAR(255) NOT NULL DEFAULT '',
  `verif` TINYINT(3) UNSIGNED NOT NULL DEFAULT 0
)
  DEFAULT CHARSET = utf8;
